<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GRiD FG3D</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>13fa2d80-8c69-4c90-9ca7-d74c1e7a12e6</testSuiteGuid>
   <testCaseLink>
      <guid>3cf9478a-c5f3-44d7-ac70-30e41fa731ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login with GEOAxIS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>79ce3cc6-644d-4394-8c62-4748068121c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FG3D Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>26e38ace-95ab-428b-8259-0d31a035153d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>3,6,76,35,78,99,200,368,400,29,67,88,99</value>
         </iterationEntity>
         <testDataId>Data Files/FG3D Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da562f93-7b11-4389-92d6-6bee68edc3d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56284034-3fc4-4c1e-bc17-5573183739a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>603f3686-cc44-4e98-b5ea-95d69d842dbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afb57c64-5ee2-4236-806e-fcbe9bda4330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3551a110-40bf-43ea-92af-a02ce4cb60fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06fda8ea-8636-4de8-959a-605f5b706b71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FG3D Test - Stragetic</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>362f56df-b723-4c44-8c01-d72e78ce82b3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data - Strategic</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ccd36a9-a9ca-46aa-bc69-bd2c7f08dcd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed5902b-dd31-4951-826b-a5cff99c6ff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf28fbf9-e795-47ba-a072-e2aca1ee2cad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d3847d2-0c10-4f39-a5f3-fb61bec611be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da4f3047-96c2-4f97-8808-08425f977115</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
